CREATE TABLE IF NOT EXISTS users (
        id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(32) NOT NULL,
        email VARCHAR(64) NOT NULL,
        password VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS devices (
        id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS vacuum_cleaners (
        id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        isOn BOOLEAN NOT NULL,
        currentLocation VARCHAR(32) NOT NULL,
        cleaningMode VARCHAR(16) NOT NULL,
        remainingBattery INT(3) UNSIGNED NOT NULL,
        serialNumber VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_HAS_DEVICE (
        id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        user_id VARCHAR(32) NOT NULL,
        device_serial VARCHAR(32) NOT NULL,
);

